#!/bin/bash

# 🏗️ Component Scaffolding Script for Lokaa App
# Generates feature modules following feature-first architecture
# Usage: ./scripts/create-component.sh ComponentName feature-name [type]

set -e

# Configuration
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
SRC_DIR="$PROJECT_ROOT/src"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Print colored output
print_info() { echo -e "${BLUE}ℹ️  $1${NC}"; }
print_success() { echo -e "${GREEN}✅ $1${NC}"; }
print_warning() { echo -e "${YELLOW}⚠️  $1${NC}"; }
print_error() { echo -e "${RED}❌ $1${NC}"; }

# Help function
show_help() {
    echo "🏗️  Lokaa Component Scaffolding Script"
    echo "=================================="
    echo ""
    echo "Usage: $0 <ComponentName> <feature-name> [type]"
    echo ""
    echo "Arguments:"
    echo "  ComponentName   - PascalCase component name (e.g., UserProfile)"
    echo "  feature-name    - kebab-case feature directory (e.g., user-management)"
    echo "  type           - Component type (optional)"
    echo ""
    echo "Component Types:"
    echo "  feature        - Full feature module with hooks, types, services (default)"
    echo "  component      - Simple component only"
    echo "  shared         - Shared component in src/shared/components"
    echo "  page           - Page component with routing"
    echo ""
    echo "Examples:"
    echo "  $0 UserProfile user-management"
    echo "  $0 Button ui shared"
    echo "  $0 NotificationCenter notifications feature"
    echo "  $0 SettingsPage settings page"
    echo ""
    echo "Generated Structure (feature type):"
    echo "  src/features/feature-name/"
    echo "  ├── components/"
    echo "  │   ├── ComponentName.tsx"
    echo "  │   └── index.ts"
    echo "  ├── hooks/"
    echo "  │   ├── useComponentName.ts"
    echo "  │   └── index.ts"
    echo "  ├── types/"
    echo "  │   ├── ComponentName.types.ts"
    echo "  │   └── index.ts"
    echo "  ├── services/"
    echo "  │   ├── ComponentNameService.ts"
    echo "  │   └── index.ts"
    echo "  ├── __tests__/"
    echo "  │   └── ComponentName.test.tsx"
    echo "  └── index.ts"
}

# Validate inputs
validate_inputs() {
    if [[ -z "$1" ]] || [[ -z "$2" ]]; then
        print_error "Missing required arguments"
        show_help
        exit 1
    fi

    # Validate component name (PascalCase)
    if [[ ! "$1" =~ ^[A-Z][a-zA-Z0-9]*$ ]]; then
        print_error "Component name must be PascalCase (e.g., UserProfile, NotificationCenter)"
        exit 1
    fi

    # Validate feature name (kebab-case)
    if [[ ! "$2" =~ ^[a-z][a-z0-9-]*$ ]]; then
        print_error "Feature name must be kebab-case (e.g., user-management, notification-center)"
        exit 1
    fi
}

# Generate TypeScript interface
generate_component_types() {
    local component_name="$1"
    local file_path="$2"
    
    cat > "$file_path" << EOF
/**
 * ${component_name} Component Types
 * Generated by Lokaa Component Scaffolding Script
 */

export interface ${component_name}Props {
  /** Optional CSS class name */
  className?: string;
  /** Component children */
  children?: React.ReactNode;
  /** Loading state */
  isLoading?: boolean;
  /** Error state */
  error?: string | null;
}

export interface ${component_name}Data {
  id: string;
  // Add your data properties here
}

export interface ${component_name}State {
  // Add your state properties here
}

export interface ${component_name}Actions {
  // Add your action types here
}
EOF
}

# Generate React component
generate_component() {
    local component_name="$1"
    local feature_name="$2"
    local file_path="$3"
    local component_type="$4"
    
    # Determine import paths based on type
    local types_import=""
    local hook_import=""
    local capitalized_type=""
    
    # Capitalize first letter of component type
    capitalized_type="$(echo "${component_type:0:1}" | tr '[:lower:]' '[:upper:]')${component_type:1}"
    
    # Lowercase component name for CSS class
    lowercase_component="$(echo "$component_name" | tr '[:upper:]' '[:lower:]')"
    
    if [[ "$component_type" == "feature" ]]; then
        types_import="import type { ${component_name}Props } from '../types';"
        hook_import="import { use${component_name} } from '../hooks';"
    elif [[ "$component_type" == "shared" ]]; then
        types_import="// Add type imports as needed"
        hook_import="// Add hook imports as needed"
    else
        types_import="// Add type imports as needed"
        hook_import="// Add hook imports as needed"
    fi
    
    cat > "$file_path" << EOF
import React from 'react';
import { cn } from '@/lib/utils';
${types_import}
${hook_import}

/**
 * ${component_name} Component
 * 
 * ${capitalized_type} component for ${feature_name} feature
 * Generated by Lokaa Component Scaffolding Script
 */
export interface ${component_name}Props {
  className?: string;
  children?: React.ReactNode;
}

export const ${component_name}: React.FC<${component_name}Props> = ({
  className,
  children,
  ...props
}) => {
  // ${capitalized_type} logic here
  // const { data, isLoading, error } = use${component_name}();

  return (
    <div 
      className={cn(
        '${feature_name}-${lowercase_component}',
        className
      )}
      {...props}
    >
      <div className="p-4">
        <h2 className="text-lg font-semibold mb-4">
          ${component_name}
        </h2>
        
        {/* Component content */}
        <div className="space-y-4">
          {children || (
            <p className="text-gray-600">
              ${component_name} component is ready for development!
            </p>
          )}
        </div>
      </div>
    </div>
  );
};

export default ${component_name};
EOF
}

# Generate custom hook
generate_hook() {
    local component_name="$1"
    local file_path="$2"
    
    cat > "$file_path" << EOF
import { useState, useEffect, useCallback } from 'react';
import type { ${component_name}Data, ${component_name}State } from '../types';

/**
 * Custom hook for ${component_name} component
 * Generated by Lokaa Component Scaffolding Script
 */
export const use${component_name} = () => {
  const [data, setData] = useState<${component_name}Data | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  // Fetch data
  const fetchData = useCallback(async () => {
    try {
      setIsLoading(true);
      setError(null);
      
      // Add your data fetching logic here
      // const result = await ${component_name}Service.getData();
      // setData(result);
      
    } catch (err) {
      setError(err instanceof Error ? err.message : 'An error occurred');
    } finally {
      setIsLoading(false);
    }
  }, []);

  // Handle actions
  const handleAction = useCallback(async (action: string) => {
    try {
      setError(null);
      
      // Add your action handling logic here
      // await ${component_name}Service.performAction(action);
      // await fetchData(); // Refresh data
      
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Action failed');
    }
  }, [fetchData]);

  // Load data on mount
  useEffect(() => {
    fetchData();
  }, [fetchData]);

  return {
    data,
    isLoading,
    error,
    fetchData,
    handleAction,
  };
};

export default use${component_name};
EOF
}

# Generate service
generate_service() {
    local component_name="$1"
    local file_path="$2"
    
    cat > "$file_path" << EOF
import { getSupabaseClient } from '@/integrations/supabase/client';
import type { ${component_name}Data } from '../types';

/**
 * ${component_name} Service
 * Handles data operations for ${component_name} component
 * Generated by Lokaa Component Scaffolding Script
 */
export class ${component_name}Service {
  private static supabase = getSupabaseClient();

  /**
   * Fetch ${component_name} data
   */
  static async getData(): Promise<${component_name}Data[]> {
    try {
      const { data, error } = await this.supabase
        .from('your_table_name') // Update table name
        .select('*');

      if (error) throw error;
      return data || [];
    } catch (error) {
      console.error('${component_name}Service.getData:', error);
      throw error;
    }
  }

  /**
   * Create new ${component_name} record
   */
  static async create(data: Partial<${component_name}Data>): Promise<${component_name}Data> {
    try {
      const { data: result, error } = await this.supabase
        .from('your_table_name') // Update table name
        .insert(data)
        .select()
        .single();

      if (error) throw error;
      return result;
    } catch (error) {
      console.error('${component_name}Service.create:', error);
      throw error;
    }
  }

  /**
   * Update ${component_name} record
   */
  static async update(id: string, data: Partial<${component_name}Data>): Promise<${component_name}Data> {
    try {
      const { data: result, error } = await this.supabase
        .from('your_table_name') // Update table name
        .update(data)
        .eq('id', id)
        .select()
        .single();

      if (error) throw error;
      return result;
    } catch (error) {
      console.error('${component_name}Service.update:', error);
      throw error;
    }
  }

  /**
   * Delete ${component_name} record
   */
  static async delete(id: string): Promise<void> {
    try {
      const { error } = await this.supabase
        .from('your_table_name') // Update table name
        .delete()
        .eq('id', id);

      if (error) throw error;
    } catch (error) {
      console.error('${component_name}Service.delete:', error);
      throw error;
    }
  }
}

export default ${component_name}Service;
EOF
}

# Generate test file
generate_test() {
    local component_name="$1"
    local feature_name="$2"
    local file_path="$3"
    
    cat > "$file_path" << EOF
import { render, screen, fireEvent, waitFor } from '@testing-library/react';
import { describe, it, expect, vi, beforeEach } from 'vitest';
import ${component_name} from '../components/${component_name}';

/**
 * ${component_name} Component Tests
 * Generated by Lokaa Component Scaffolding Script
 */

// Mock the hook
vi.mock('../hooks/use${component_name}', () => ({
  use${component_name}: () => ({
    data: null,
    isLoading: false,
    error: null,
    fetchData: vi.fn(),
    handleAction: vi.fn(),
  }),
}));

describe('${component_name}', () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it('renders without crashing', () => {
    render(<${component_name} />);
    expect(screen.getByText('${component_name}')).toBeInTheDocument();
  });

  it('applies custom className', () => {
    const { container } = render(<${component_name} className="custom-class" />);
    expect(container.firstChild).toHaveClass('custom-class');
  });

  it('renders children when provided', () => {
    render(
      <${component_name}>
        <div>Custom content</div>
      </${component_name}>
    );
    expect(screen.getByText('Custom content')).toBeInTheDocument();
  });

  it('shows default content when no children provided', () => {
    render(<${component_name} />);
    expect(screen.getByText('${component_name} component is ready for development!')).toBeInTheDocument();
  });

  // Add more specific tests here
  it.todo('handles loading state correctly');
  it.todo('handles error state correctly');
  it.todo('handles user interactions correctly');
});
EOF
}

# Generate index file
generate_index() {
    local component_name="$1"
    local file_path="$2"
    local type="$3"
    
    case "$type" in
        "components")
            cat > "$file_path" << EOF
/**
 * ${component_name} Components Export
 * Generated by Lokaa Component Scaffolding Script
 */

export { ${component_name}, default } from './${component_name}';
export type { ${component_name}Props } from './${component_name}';
EOF
            ;;
        "hooks")
            cat > "$file_path" << EOF
/**
 * ${component_name} Hooks Export
 * Generated by Lokaa Component Scaffolding Script
 */

export { use${component_name}, default } from './use${component_name}';
EOF
            ;;
        "types")
            cat > "$file_path" << EOF
/**
 * ${component_name} Types Export
 * Generated by Lokaa Component Scaffolding Script
 */

export type {
  ${component_name}Props,
  ${component_name}Data,
  ${component_name}State,
  ${component_name}Actions,
} from './${component_name}.types';
EOF
            ;;
        "services")
            cat > "$file_path" << EOF
/**
 * ${component_name} Services Export
 * Generated by Lokaa Component Scaffolding Script
 */

export { ${component_name}Service, default } from './${component_name}Service';
EOF
            ;;
        "feature")
            cat > "$file_path" << EOF
/**
 * ${component_name} Feature Export
 * Generated by Lokaa Component Scaffolding Script
 */

// Components
export { ${component_name} } from './components';
export type { ${component_name}Props } from './components';

// Hooks
export { use${component_name} } from './hooks';

// Types
export type {
  ${component_name}Data,
  ${component_name}State,
  ${component_name}Actions,
} from './types';

// Services
export { ${component_name}Service } from './services';
EOF
            ;;
    esac
}

# Create directory structure
create_directories() {
    local base_path="$1"
    local component_type="$2"
    
    case "$component_type" in
        "feature")
            mkdir -p "$base_path/components"
            mkdir -p "$base_path/hooks"
            mkdir -p "$base_path/types"
            mkdir -p "$base_path/services"
            mkdir -p "$base_path/__tests__"
            ;;
        "shared")
            mkdir -p "$base_path"
            ;;
        "component"|"page")
            mkdir -p "$base_path"
            ;;
    esac
}

# Main scaffolding function
scaffold_component() {
    local component_name="$1"
    local feature_name="$2"
    local component_type="${3:-feature}"
    
    print_info "Creating ${component_type} component: ${component_name}"
    
    # Determine base path
    local base_path
    case "$component_type" in
        "shared")
            base_path="$SRC_DIR/shared/components/$feature_name"
            ;;
        "page")
            base_path="$SRC_DIR/views"
            ;;
        *)
            base_path="$SRC_DIR/features/$feature_name"
            ;;
    esac
    
    # Check if feature already exists
    if [[ -d "$base_path" ]] && [[ "$component_type" == "feature" ]]; then
        print_warning "Feature directory already exists: $base_path"
        echo -n "Continue and potentially overwrite files? (y/N): "
        read -r response
        if [[ ! "$response" =~ ^[Yy]$ ]]; then
            print_info "Cancelled"
            exit 0
        fi
    fi
    
    # Create directory structure
    create_directories "$base_path" "$component_type"
    
    # Generate files based on type
    case "$component_type" in
        "feature")
            # Types
            generate_component_types "$component_name" "$base_path/types/${component_name}.types.ts"
            generate_index "$component_name" "$base_path/types/index.ts" "types"
            
            # Component
            generate_component "$component_name" "$feature_name" "$base_path/components/${component_name}.tsx" "$component_type"
            generate_index "$component_name" "$base_path/components/index.ts" "components"
            
            # Hook
            generate_hook "$component_name" "$base_path/hooks/use${component_name}.ts"
            generate_index "$component_name" "$base_path/hooks/index.ts" "hooks"
            
            # Service
            generate_service "$component_name" "$base_path/services/${component_name}Service.ts"
            generate_index "$component_name" "$base_path/services/index.ts" "services"
            
            # Test
            generate_test "$component_name" "$feature_name" "$base_path/__tests__/${component_name}.test.tsx"
            
            # Main index
            generate_index "$component_name" "$base_path/index.ts" "feature"
            ;;
            
        "shared")
            generate_component "$component_name" "$feature_name" "$base_path/${component_name}.tsx" "$component_type"
            generate_test "$component_name" "$feature_name" "$base_path/${component_name}.test.tsx"
            ;;
            
        "component"|"page")
            generate_component "$component_name" "$feature_name" "$base_path/${component_name}.tsx" "$component_type"
            generate_test "$component_name" "$feature_name" "$base_path/${component_name}.test.tsx"
            ;;
    esac
    
    print_success "Successfully created ${component_type} component: ${component_name}"
    print_info "Location: $base_path"
    
    # Show next steps
    echo ""
    print_info "Next steps:"
    case "$component_type" in
        "feature")
            echo "  1. Update database table name in ${component_name}Service.ts"
            echo "  2. Define proper types in ${component_name}.types.ts"
            echo "  3. Implement business logic in use${component_name}.ts"
            echo "  4. Design the UI in ${component_name}.tsx"
            echo "  5. Add tests in __tests__/${component_name}.test.tsx"
            echo ""
            echo "Import in your app:"
            echo "  import { ${component_name} } from '@/features/${feature_name}';"
            ;;
        "shared")
            echo "  1. Implement the shared component logic"
            echo "  2. Add proper TypeScript types"
            echo "  3. Update shared components index file"
            echo ""
            echo "Import in your app:"
            echo "  import { ${component_name} } from '@/shared/components/${feature_name}';"
            ;;
        *)
            echo "  1. Implement the component logic"
            echo "  2. Add proper TypeScript types"
            echo "  3. Add to your routing or parent component"
            ;;
    esac
}

# Main execution
main() {
    # Check if help is requested
    if [[ "$1" == "-h" ]] || [[ "$1" == "--help" ]]; then
        show_help
        exit 0
    fi
    
    # Validate inputs
    validate_inputs "$@"
    
    local component_name="$1"
    local feature_name="$2"
    local component_type="${3:-feature}"
    
    # Validate component type
    case "$component_type" in
        "feature"|"component"|"shared"|"page")
            ;;
        *)
            print_error "Invalid component type: $component_type"
            echo "Valid types: feature, component, shared, page"
            exit 1
            ;;
    esac
    
    print_info "🏗️  Lokaa Component Scaffolding"
    print_info "Component: $component_name"
    print_info "Feature: $feature_name"
    print_info "Type: $component_type"
    echo ""
    
    # Create the component
    scaffold_component "$component_name" "$feature_name" "$component_type"
}

# Execute if script is run directly
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main "$@"
fi
