import { log } from '@/utils/logger';
import { PostgrestError } from '@supabase/supabase-js'
import { getSupabaseClient } from '@/integrations/supabase/client'
import { generateSlug } from '@/utils/slugUtils'
import { Database } from "@/types/supabase"
import { clearAllAuthTokens } from '@/utils/auth/authTokenUtils'

// Import User type from sessionUtils to maintain consistency
import { User } from './sessionUtils'

/**
 * Fetch user details from public.users table
 */
export const fetchUserDetails = async (userId: string): Promise<Database['public']['Tables']['users']['Row'] | null> => {
  try {
    log.debug('Utils', 'AuthContext: Fetching user details for ID:', userId);
    const { data, error } = await getSupabaseClient()
      .from('users')
      .select('*')
      .eq('id', userId)
      .single();
      
    if (error) {
      log.error('Utils', 'AuthContext: Error fetching user details:', error);
      throw error;
    }
    
    if (data) {
      log.debug('Utils', 'AuthContext: User details loaded:', {
        id: data.id,
        full_name: data.full_name,
        profile_url: data.profile_url
      });
      return data;
    } else {
      log.warn('Utils', 'AuthContext: No user details found for ID:', userId);
      return null;
    }
  } catch (error) {
    log.error('Utils', 'AuthContext: Error in fetchUserDetails:', error);
    return null;
  }
};

/**
 * Generate a unique user URL slug
 */
export async function generateUniqueUserSlug(user: User): Promise<string | null> {
  if (!user) return null;

  // Destructure needed properties to simplify type inference
  const userId = user.id;
  const userEmail = user.email;
  const meta = user.user_metadata;

  // Type assertions for clarity
  const username = meta.username as string | undefined;
  const firstName = meta.firstName as string | undefined;
  const lastName = meta.lastName as string | undefined;
  const fullName = meta.full_name as string | undefined;

  // Try username, email prefix, full name, or fallback to user id
  const potentialBases: (string | undefined | null)[] = [
    username,
    userEmail?.split('@')[0],
    (firstName && lastName) ? `${firstName}-${lastName}` : null,
    fullName,
    userId
  ];
  const baseCandidates: string[] = potentialBases.filter((s): s is string => typeof s === 'string' && s.length > 0);

  for (const base of baseCandidates) {
    let slug = generateSlug(base);
    let unique = false;
    let attempt = 0;
    let candidate = slug;
    while (!unique && attempt < 5) {
      try {
        // Check uniqueness in users table with a simpler approach
        const { data, error } = await getSupabaseClient()
          .from('users')
          .select('id')
          .eq('profile_url', candidate)
          .limit(1);

        if (error) {
          log.warn('Utils', 'Error checking URL uniqueness:', error);
          break;
        }

        if (!data || data.length === 0) {
          unique = true;
          slug = candidate;
          break;
        }
        
        // If not unique, append a short random string
        candidate = `${slug}-${Math.floor(1000 + Math.random() * 9000)}`;
        attempt++;
      } catch (err) {
        log.error('Utils', 'Exception checking URL uniqueness:', err);
        break;
      }
    }
    if (unique) return slug;
  }
  // Fallback: user id
  return user.id;
}

// FIXED: Add user URL cache to prevent repeated RPC calls
const userUrlCache = new Map<string, { url: string; timestamp: number }>();
const URL_CACHE_TTL = 10 * 60 * 1000; // 10 minutes

/**
 * Get cached user URL or fetch from database if needed
 */
export const getCachedUserUrl = async (userId: string): Promise<string | null> => {
  // Check cache first
  const cached = userUrlCache.get(userId);
  if (cached && Date.now() - cached.timestamp < URL_CACHE_TTL) {
    return cached.url;
  }

  try {
    // Fetch directly from users table instead of RPC
    const { data, error } = await getSupabaseClient()
      .from('users')
      .select('profile_url')
      .eq('id', userId)
      .single();
      
    if (error) {
      log.error('Utils', 'Error fetching user URL:', error);
      return null;
    }
    
    if (data?.profile_url) {
      // Cache the result
      userUrlCache.set(userId, {
        url: data.profile_url,
        timestamp: Date.now()
      });
      return data.profile_url;
    }
    
    return null;
  } catch (error) {
    log.error('Utils', 'Error in getCachedUserUrl:', error);
    return null;
  }
};

/**
 * DEPRECATED: Ensure user has a URL by calling the database function
 * This function caused 406 errors due to RLS policies. Profile URLs are now
 * automatically generated by database triggers on user creation.
 * Use getCachedUserUrl instead for reading URLs.
 */
export const ensureUserUrl = async (
  userId: string,
  setUser: (updater: (prevUser: any) => any) => void
): Promise<void> => {
  log.warn('Utils', 'ensureUserUrl is deprecated - profile URLs are set by database triggers');
  
  // FIXED: Instead of calling RPC, just get the existing URL from cache/database
  const userUrl = await getCachedUserUrl(userId);
  
  if (userUrl) {
    log.debug('Utils', 'User URL retrieved from cache/database:', userUrl);
    setUser(prevUser => {
      if (prevUser && prevUser.url !== userUrl) {
        return { ...prevUser, url: userUrl };
      }
      return prevUser;
    });
  }
};

/**
 * Clear all storage items on sign out
 */
export const clearAuthStorage = (): void => {
  log.debug('Utils', '🧹 Immediately clearing client-side session state and storage...');
  
  // PHASE 3 FIX: Use centralized auth token cleanup for consistent localStorage management
  log.debug('Utils', '🧹 [Phase 3] Clearing problematic auth tokens...');
  clearAllAuthTokens(false); // Clear all auth tokens including Supabase keys during logout
  
  // Clear localStorage items
  const localItemsToClear = [
    'selectedSpaceId', 
    'lastVisitedSpace',
    'lastCreatedSpace',
    'spaceData',
    // PHASE 3 FIX: Removed problematic key 'getSupabaseClient().auth.token' - handled by clearAllAuthTokens()
    // Smart redirect cache keys - CRITICAL for preventing cross-user space access
    'lastActiveSpace',
    'ownedSpaces',
    'memberSpaces', 
    'lastRedirectTimestamp',
    'lastJoinedSpace'
  ];
  
  localItemsToClear.forEach(item => {
    try {
      localStorage.removeItem(item);
      log.debug('Utils', `🧹 Cleared localStorage item: ${item}`);
    } catch (e) {
      log.warn('Utils', `Failed to remove ${item} from localStorage:`, e);
    }
  });
  
  // CRITICAL: Clear space ownership and membership cache items to prevent unauthorized access
  try {
    Object.keys(localStorage)
      .filter(key => key.startsWith('user_owns_space_') || key.startsWith('user_member_') || key.startsWith('setupGuideDismissed_'))
      .forEach(key => {
        log.debug('Utils', `🧹 Clearing space cache item: ${key}`);
        localStorage.removeItem(key);
      });
  } catch (e) {
    log.warn('Utils', 'Failed to clear space cache items:', e);
  }
  
  // Clear sessionStorage items
  const sessionItemsToClear = [
    'selectedSpaceId', 
    'spaceData', 
    'redirect_after_login', 
    'coming_from_space_switcher',
    'userWantsDiscover',
    'active_tab_' // Prefix for active tab storage
  ];
  
  sessionItemsToClear.forEach(item => {
    try {
      // For prefix items, remove all matching items
      if (item.endsWith('_')) {
        Object.keys(sessionStorage)
          .filter(key => key.startsWith(item))
          .forEach(matchingKey => {
            log.debug('Utils', `Removing session storage item with prefix ${item}:`, matchingKey);
            sessionStorage.removeItem(matchingKey);
          });
      } else {
        sessionStorage.removeItem(item);
        log.debug('Utils', `🧹 Cleared sessionStorage item: ${item}`);
      }
    } catch (e) {
      log.warn('Utils', `Failed to remove ${item} from sessionStorage:`, e);
    }
  });
  
  // PHASE 3 FIX: Supabase key cleanup now handled by clearAllAuthTokens() above
  // This eliminates duplicate and inconsistent localStorage management
  
  log.debug('Utils', '✅ Storage cleanup completed - all user-specific data cleared');
}; 