// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nmddvthcsyppyjncqfsk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5tZGR2dGhjc3lwcHlqbmNxZnNrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0ODg4MTYsImV4cCI6MjA2MDA2NDgxNn0.NMzMDvaOD2vHfBfjRbuit05EIdi7QK9pC_ChzX3klG0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Add debug logs to client initialization
console.log('🔌 Initializing Supabase client with URL:', import.meta.env.VITE_SUPABASE_URL);
console.log('🔌 Supabase API key format:', 
  import.meta.env.VITE_SUPABASE_ANON_KEY ? 
  `${import.meta.env.VITE_SUPABASE_ANON_KEY.substring(0, 5)}...${import.meta.env.VITE_SUPABASE_ANON_KEY.substring(import.meta.env.VITE_SUPABASE_ANON_KEY.length - 5)}` :
  'Missing API key'
);

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);